version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        env_file:
            - .env
        ports:
            - "7000:7000"
        volumes:
            - ./data:/app/db
